#!/usr/bin/env node
/**
 * news-radar - AI新闻雷达
 * 自动抓取AI/科技热点，生成每日简报
 */

const AI_KEYWORDS = [
    'ai', 'aigc', 'llm', 'gpt', 'claude', 'gemini',
    'deepseek', 'openai', 'anthropic', 'transformer',
    'agent', 'diffusion', 'prompt',
    '大模型', '人工智能', '机器学习', '深度学习', '智能体'
];

const NEWS_SOURCES = [
    { name: 'HackerNews', type: 'api', url: 'https://hacker-news.firebaseio.com/v0/topstories.json' },
    { name: 'GitHub', type: 'api', url: 'https://api.github.com/search/repositories?q=ai+created:>2024-01-01&sort=stars&per_page=20' },
    { name: 'TechCrunch', type: 'rss', url: 'https://techcrunch.com/feed/' },
    { name: 'MIT Tech Review', type: 'rss', url: 'https://www.technologyreview.com/feed/' },
];

function normalizeUrl(url) {
    try {
        const u = new URL(url);
        ['utm_source', 'utm_medium', 'utm_campaign', 'fbclid', 'gclid'].forEach(p => u.searchParams.delete(p));
        return u.toString().replace(/\/$/, '');
    } catch {
        return url;
    }
}

function isAIRelated(title, source) {
    const text = `${title} ${source}`.toLowerCase();
    return AI_KEYWORDS.some(k => text.includes(k.toLowerCase()));
}

async function fetchSource(source) {
    // 实现抓取逻辑
    return [];
}

async function fetchAllNews() {
    const results = await Promise.all(NEWS_SOURCES.map(fetchSource));
    return results.flat();
}

function dedupe(items) {
    const seen = new Set();
    return items.filter(item => {
        const key = normalizeUrl(item.url) + '||' + item.title;
        if (seen.has(key)) return false;
        seen.add(key);
        return true;
    });
}

function filterAI(items) {
    return items.filter(item => isAIRelated(item.title, item.source));
}

function generateReport(items) {
    const date = new Date().toISOString().split('T')[0];
    return `# 🤖 AI Daily News - ${date}

## Today's Top ${items.length} AI News

${items.map((item, i) => 
`### ${i + 1}. ${item.title}
- Source: ${item.source}
- Time: ${item.published}
- [Read more](${item.url})
`).join('\n')}

---
Generated by News Radar | Total: ${items.length} articles
`;
}

module.exports = {
    fetchAllNews,
    filterAI,
    dedupe,
    generateReport
};
